"""A fourth pass on the Labor page, from a live screenshot + follow-up
feedback round:

- The week radar's "over target" flag text was still ember/orange (the
  default color for .lb2-sg .k i) because renderWeekRadar() only ever set
  its textContent, never a .bad class, even though that class (and its
  red color) already existed in CSS for exactly this state.
- The worst-day callout bubble on the labor ribbon chart is a fixed
  200px-wide box centered on its anchor point via translate(-50%,-100%).
  A 6% left-clamp let a worst day early in the period push the bubble's
  left edge past the chart's own inset, landing it visibly further left
  than the "% of sales" figure above it instead of lining up with it.
- Every Schedule History row rendered a blue "AI" badge on any
  non-edited week — pure noise, since a row without "Edited" is AI-
  generated by definition.
- The row's one-line AI summary was truncated twice over: once at 110
  chars server-side (models._history_summary_line), then again by CSS
  text-overflow:ellipsis on top of that — cutting off complete sentences
  the engine actually produced (which routinely run 110-160 chars).
- "21 hr ago" sat inline inside the row's top line (.rtop), while its
  neighbors (the quality pill, hours, action icons) are separate grid
  columns vertically centered against the row's full two-line height —
  so the timestamp always looked pinned too high relative to them.
- #sched-history-detail (the expanded view of a saved schedule) used the
  same flat var(--hb-tint) wash already fixed for Employee Availability/
  Operational Score, with the same "undefined brown smear" problem.
- The "Building the week" loading state (cavnarWeekHtml) rendered at a
  fixed 270px wide regardless of the panel's real width, looking cramped
  next to the rest of the schedule card.
- The preview panel's "Close" button was cbtn-sm while its siblings
  (Download CSV, Send to staff) were default-sized — visibly smaller.
- "Send to staff" only ever opened the email-contacts drawer
  (openPublishSchedule) with no way to collapse it again short of the
  outer "Close", which threw away the whole generated schedule instead
  of just hiding the email list. Generation also never refreshed the
  on-screen history list, so a freshly generated (and already-saved)
  schedule looked like it had vanished until the page was reloaded.
- The email-contacts drawer's text (employee names, email inputs, the
  "N of M reachable" result line) was set in the 11.5-12px range, well
  below the rest of the app's body-text scale.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHBOARD = os.path.join(ROOT, "templates", "dashboard.html")


def _src():
    return open(DASHBOARD, encoding="utf-8").read()


def _fn(name):
    s = _src()
    m = re.search(r"function %s\(" % re.escape(name), s) or \
        re.search(r"window\.%s\s*=\s*function\(" % re.escape(name), s)
    assert m, "function not found: " + name
    i = s.index("{", m.start())
    depth = 0
    for j in range(i, len(s)):
        if s[j] == "{":
            depth += 1
        elif s[j] == "}":
            depth -= 1
            if depth == 0:
                return s[m.start():j + 1]
    raise AssertionError("unbalanced braces in " + name)


# ── week radar's "over target" flag reads red, not the default ember ───────

def test_week_radar_flag_gets_the_bad_class_when_over_target():
    body = _fn("renderWeekRadar")
    assert "flag.className=_over?'bad':''" in body.replace(" ", "")


# ── worst-day callout no longer overhangs the chart's own left inset ───────

def test_callout_left_clamp_keeps_the_bubble_inside_the_chart():
    body = _fn("_laborCallout")
    assert "Math.max(12,Math.min(88," in body.replace(" ", "")


# ── no more blue "AI" pill on every unedited row ────────────────────────────

def test_no_ai_badge_on_history_rows():
    body = _fn("_schedHistRowHtml")
    assert '"badge ai"' not in body
    css = _src()
    assert ".lb2-hist .badge.ai" not in css


# ── the row's AI summary line is allowed to show in full ───────────────────

def test_row_text_wraps_instead_of_css_ellipsis_truncating():
    css = _src()
    m = re.search(r"\.lb2-hist \.rline \.rtxt\{([^}]*)\}", css)
    assert m
    rule = m.group(1)
    assert "ellipsis" not in rule and "nowrap" not in rule


# ── "N ago" is centered with its row-siblings, not pinned to the top line ──

def test_rgen_is_its_own_grid_column_not_inline_in_rtop():
    body = _fn("_schedHistRowHtml")
    # rgen must render as a sibling of .rmain (its own grid item), not
    # nested inside .rtop alongside the week label and badge — otherwise it
    # sits pinned to the row's top line instead of centered like its
    # grid-column siblings (.rside, .ractions).
    rtop_idx = body.index('class="rtop"')
    rgen_idx = body.index('class="rgen"')
    rmain_close = body.index("</div></div>", rtop_idx)
    assert rgen_idx > rmain_close, "rgen should sit outside .rmain, not inside .rtop"
    css = _src()
    m = re.search(r"\.lb2-hist \.row\{([^}]*)\}", css)
    assert "grid-template-columns:1fr auto auto auto" in m.group(1)


# ── the expanded schedule view is branded, not a flat tint ─────────────────

def test_sched_history_detail_uses_the_branded_gradient():
    css = _src()
    m = re.search(r"#sched-history-detail\{([^}]*)\}", css)
    assert m, "missing #sched-history-detail rule"
    rule = m.group(1)
    assert "var(--hb-tint)" not in rule
    assert "linear-gradient" in rule and "border:1px solid" in rule


# ── the "building the week" loader is sized to its real container ──────────

def test_week_loader_svg_is_wider_than_before():
    body = _fn("cavnarWeekHtml")
    assert 'width="500"' in body
    assert 'width="270"' not in body


# ── generated-schedule action buttons match sizes ───────────────────────────

def test_close_button_is_not_undersized_next_to_its_siblings():
    s = _src()
    i = s.index("AI-Optimized Schedule")
    j = s.index("</div>\n      </div>", i)
    block = s[i:j]
    assert 'cbtn cbtn-glass cbtn-sm"' not in block
    assert 'cbtn cbtn-glass"' in block


# ── the email drawer can be collapsed, and generating doesn't lose data ────

def test_send_to_staff_button_toggles_instead_of_only_opening():
    s = _src()
    assert 'onclick="togglePublishSchedule()"' in s
    body = _fn("togglePublishSchedule")
    assert "panel.style.display = 'none'" in body


def test_publish_panel_has_an_explicit_collapse_control():
    s = _src()
    i = s.index('id="publish-sched-panel"')
    j = s.index('id="ps-contacts"', i)
    header = s[i:j]
    assert "togglePublishSchedule()" in header


def test_generation_result_refreshes_the_on_screen_history_list():
    body = _fn("_schedHandleResult")
    assert "loadScheduleHistory()" in body


# ── the email drawer's text matches the app's normal reading size ──────────

def test_staff_contact_rows_use_a_readable_font_size_not_11px():
    body = _fn("openPublishSchedule")
    assert "font-size:12px" not in body
    assert "font-size:11.5px" not in body
    assert "font-size:14px" in body


# ── "What counts most" sliders — the native track/number read as bright
# white against the dark theme; both swap to the same warm cream/sand
# already used everywhere else literal white shows through in dark mode ──

def test_the_weighting_sliders_and_their_numbers_carry_the_sand_classes():
    body = _fn("renderWeightList")
    assert 'class="qw-slider"' in body
    assert 'class="qw-num"' in body


def test_dark_mode_swaps_the_slider_track_and_number_to_sand_not_white():
    css = _src()
    assert '[data-theme="dark"] .qw-num{color:#ddd0b8' in css
    assert '[data-theme="dark"] .qw-slider::-webkit-slider-runnable-track{background:#ddd0b8}' in css
    assert '[data-theme="dark"] .qw-slider::-moz-range-track{background:#ddd0b8}' in css
