import Foundation
import Observation

struct ScheduleHistoryEntry: Codable, Identifiable, Hashable {
    let id: Int
    let generatedAt: String
    let weekStart: String?
    let weekEnd: String?
    let hoursScheduled: Double?
    let hoursBudget: Double?
    let laborTarget: Double?

    enum CodingKeys: String, CodingKey {
        case id
        case generatedAt = "generated_at"
        case weekStart = "week_start"
        case weekEnd = "week_end"
        case hoursScheduled = "hours_scheduled"
        case hoursBudget = "hours_budget"
        case laborTarget = "labor_target"
    }
}

@Observable
@MainActor
final class ScheduleHistoryViewModel {
    var history: [ScheduleHistoryEntry] = []
    var isLoading = false
    var errorMessage: String?
    // Deliberately separate from errorMessage above — that one gates
    // whether the List renders at all (see ScheduleHistoryView.body),
    // so a failed delete setting the SAME property was replacing the
    // entire list with a full-screen error the moment one swipe-delete
    // failed, rather than surfacing just that one failure.
    var deleteErrorMessage: String?

    private let client: APIClient
    init(client: APIClient = .shared) {
        self.client = client
    }

    private struct Response: Decodable {
        let ok: Bool
        let history: [ScheduleHistoryEntry]
    }

    func load() async {
        isLoading = true
        errorMessage = nil
        defer { isLoading = false }
        do {
            let response: Response = try await client.send("/mobile/api/labor/schedule-history")
            history = response.history
        } catch let error as APIClient.APIError {
            errorMessage = error.message
        } catch is CancellationError {
            // The screen went away mid-load — not a failure (CLIENT-49).
        } catch {
            errorMessage = "Couldn't load schedule history."
        }
    }

    private typealias OkResponse = APIClient.OKResponse

    /// The only way a schedule ever leaves this list — nothing here or
    /// server-side removes one automatically (see delete_schedule_history's
    /// own doc comment). Removes locally on success rather than a full
    /// reload, so swipe-to-delete's row-removal animation stays smooth.
    func delete(id: Int) async {
        do {
            let _: OkResponse = try await client.send(
                "/mobile/api/labor/schedule-history/\(id)", method: .delete
            )
            history.removeAll { $0.id == id }
            Haptic.selection()
        } catch let error as APIClient.APIError {
            // The real underlying message (e.g. a specific status code),
            // not a hardcoded string — needed to actually diagnose why a
            // delete is failing rather than guessing at it blind.
            deleteErrorMessage = error.message
        } catch {
            deleteErrorMessage = "Couldn't delete that schedule."
        }
    }
}

/// One saved version of a week: generated, edited, fixes or published,
/// who saved it and what it changed against the one before.
struct ScheduleVersion: Codable, Identifiable, Equatable {
    let id: Int
    let version: Int
    let reason: String?
    let savedBy: String?
    let createdAt: String?
    let changes: Int?
    let lines: [String]?
    let score: Int?

    enum CodingKeys: String, CodingKey {
        case id, version, reason, changes, lines, score
        case savedBy = "saved_by"
        case createdAt = "created_at"
    }

    var isPublished: Bool { reason == "published" }

    /// "generated by Cavnar AI" · "edited by will" · "published"
    var title: String {
        let who = (savedBy ?? "").isEmpty ? nil : savedBy
        switch reason {
        case "generated": return "generated by \(who ?? "Cavnar AI")"
        case "edited": return who.map { "edited by \($0)" } ?? "edited"
        case "fixes": return who.map { "fixes applied by \($0)" } ?? "fixes applied"
        case "published": return who.map { "published by \($0)" } ?? "published"
        default: return [reason, who.map { "by \($0)" }].compactMap { $0 }.joined(separator: " ")
        }
    }
}

/// How the week that went out differs from the one the engine drafted.
struct DraftVsPublished: Codable, Equatable {
    let available: Bool?
    let changes: Int?
    let added: Int?
    let removed: Int?
    let moved: Int?
    let retimed: Int?
    let hoursBefore: Double?
    let hoursAfter: Double?
    let lines: [String]?

    enum CodingKeys: String, CodingKey {
        case available, changes, added, removed, moved, retimed, lines
        case hoursBefore = "hours_before"
        case hoursAfter = "hours_after"
    }

    /// "3 changes · 2 moved, 1 retimed · 212h → 218h"
    var summaryLine: String? {
        guard let changes, changes > 0 else { return nil }
        var kinds: [String] = []
        if let n = added, n > 0 { kinds.append("\(n) added") }
        if let n = removed, n > 0 { kinds.append("\(n) removed") }
        if let n = moved, n > 0 { kinds.append("\(n) moved") }
        if let n = retimed, n > 0 { kinds.append("\(n) retimed") }
        var parts = ["\(changes) \(changes == 1 ? "change" : "changes")"]
        if !kinds.isEmpty { parts.append(kinds.joined(separator: ", ")) }
        if let a = hoursBefore, let b = hoursAfter, a != b {
            parts.append("\(a.commaFormatted)h → \(b.commaFormatted)h")
        }
        return parts.joined(separator: " · ")
    }
}

/// Detail reuses GeneratedSchedule (defined in LaborViewModel.swift) —
/// the history detail endpoint returns the same shape (schedule_csv,
/// summary, preview_rows, hours_scheduled/budget) plus a few extra fields
/// (id, generated_at, week_start/end) that Decodable simply ignores.
@Observable
@MainActor
final class ScheduleHistoryDetailViewModel {
    var detail: GeneratedSchedule?
    var isLoading = false
    var errorMessage: String?
    var versions: [ScheduleVersion] = []
    var draftVsPublished: DraftVsPublished?
    var versionsError: String?

    private let client: APIClient

    // Tracks which id is currently loaded/loading so a second .task/
    // onAppear firing for the same id (see ScheduleHistoryDetailView's
    // belt-and-suspenders comment) is a harmless no-op instead of
    // re-fetching or racing the first call.
    private var loadedID: Int?

    // Passing an id here kicks off the load immediately at construction
    // time, instead of waiting on a view lifecycle callback. This app has
    // repeatedly hit cases where .task/.onAppear don't reliably fire (or
    // resolve) for a view pushed from a List row's NavigationLink — see
    // ScheduleHistoryDetailView's own .task+.onAppear belt-and-suspenders
    // comment, added for exactly that reason and evidently still not
    // 100% reliable on its own (this was the "blank page" bug). Starting
    // the load here removes the dependency on view lifecycle timing
    // entirely for the common case; .task/.onAppear stay in place as
    // redundant, harmless no-ops via the loadedID guard in load() below.
    // The default nil keeps the existing test-only `client:`-only
    // initializer (see ScheduleHistoryViewModelTests) from auto-firing a
    // load neither test wants.
    init(id: Int? = nil, client: APIClient = .shared) {
        self.client = client
        if let id {
            Task { await self.load(id: id) }
        }
    }

    func load(id: Int) async {
        guard loadedID != id || (detail == nil && errorMessage == nil) else { return }
        loadedID = id
        isLoading = true
        errorMessage = nil
        defer { isLoading = false }
        do {
            // Explicit non-optional local, not a direct assignment into
            // the optional `detail` property — matches every other
            // load() in this codebase (see LaborViewModel.pollSchedule).
            // Assigning straight into an Optional-typed property lets the
            // compiler infer send<Response>'s Response as GeneratedSchedule?
            // instead of GeneratedSchedule, decoding the JSON as a
            // top-level Optional rather than the concrete type.
            let fetched: GeneratedSchedule = try await client.send("/mobile/api/labor/schedule-history/\(id)")
            detail = fetched
        } catch let error as APIClient.APIError {
            errorMessage = error.message
        } catch is CancellationError {
            // The screen went away mid-load — not a failure (CLIENT-49).
        } catch {
            errorMessage = "Couldn't load this schedule."
        }
    }

    private struct VersionsResponse: Decodable {
        let ok: Bool
        let versions: [ScheduleVersion]?
        let draftVsPublished: DraftVsPublished?
        let error: String?
        enum CodingKeys: String, CodingKey {
            case ok, versions, error
            case draftVsPublished = "draft_vs_published"
        }
    }

    /// The week's version trail. Secondary to the detail itself — a
    /// failure here leaves the timeline out rather than the whole screen.
    func loadVersions(id: Int) async {
        do {
            let r: VersionsResponse = try await client.send(
                "/mobile/api/labor/schedule-history/\(id)/versions", hapticOnError: false)
            guard r.ok else { versionsError = r.error; return }
            versions = (r.versions ?? []).sorted { $0.version < $1.version }
            draftVsPublished = r.draftVsPublished
            versionsError = nil
        } catch is CancellationError {
        } catch {
            versionsError = "Couldn't load this week's versions."
        }
    }
}
